project:
  type: book

book:
  title: "Introduction to Business Statistics: A Modeling Approach"
  author: "Viswa Viswanathan"
  date: "1/15/2026"
  chapters:
    - index.qmd
    - preface.qmd

    - part: "Data, Visualization, and Patterns"
      chapters:
        - modules/01-data-visualization/01-overview.qmd
        - modules/01-data-visualization/data-frames.qmd
        - modules/01-data-visualization/point-plots.qmd
        

    - part: "Variation"
      chapters:
        - modules/02-variability/02-overview.qmd
        - modules/02-variability/violin-plots.qmd
        - modules/02-variability/variance-and-sd.qmd
        
    - part: "Introduction to models"
      chapters:
        - modules/03-introduction-to-models/03-overview.qmd
        - modules/03-introduction-to-models/path-to-models-story.qmd
        - modules/03-introduction-to-models/category-means-story.qmd
        - modules/03-introduction-to-models/intro-to-models.qmd
        - modules/03-introduction-to-models/visualizing-simple-models.qmd

    - part: "More on models -- least squares"
      chapters:
        - modules/04-more-on-models/04-overview.qmd
        - modules/04-more-on-models/line-of-best-fit-story.qmd
        - modules/04-more-on-models/visualizing-models.qmd
        - modules/04-more-on-models/finding-the-model-function.qmd
        - modules/04-more-on-models/model-with-cat-and-num-explanatories-story.qmd
    - part: "Explanatory Power of a Model"
      chapters: 
        - modules/05-explanatory-power-of-models/05-overview.qmd
        - modules/05-explanatory-power-of-models/explain-as-used-in-statistics.qmd
        - modules/05-explanatory-power-of-models/variance-analysis.qmd
        - modules/05-explanatory-power-of-models/accounting-for-variance.qmd
  sidebar:
    style: docked
    background: light
    logo: images/logo-dark.png

  search: true

format:
  html:
    theme: 
      - flatly
      - custom.scss
    toc: true
    toc-depth: 3
    
    number-sections: true
    code-tools: false
    df-print: paged
    

  pdf:
    listings: true
    documentclass: scrreprt
    include-in-header: header.tex
    toc: true
    toc-depth: 3
    number-sections: true
    geometry: "margin=1in"
    callout-appearance: boxed
    fontsize: 12pt
    highlight-style: pygments

# bibliography: references.bib
# csl: apa.csl

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
